export const algeriaWilayas = [
  { id: 1, nameAr: 'أدرار', nameEn: 'Adrar', homePrice: 1200, deskPrice: 800 },
  { id: 2, nameAr: 'الشلف', nameEn: 'Chlef', homePrice: 800, deskPrice: 500 },
  { id: 3, nameAr: 'الأغواط', nameEn: 'Laghouat', homePrice: 900, deskPrice: 600 },
  { id: 4, nameAr: 'أم البواقي', nameEn: 'Oum El Bouaghi', homePrice: 850, deskPrice: 550 },
  { id: 5, nameAr: 'باتنة', nameEn: 'Batna', homePrice: 850, deskPrice: 550 },
  { id: 6, nameAr: 'بجاية', nameEn: 'Béjaïa', homePrice: 800, deskPrice: 500 },
  { id: 7, nameAr: 'بسكرة', nameEn: 'Biskra', homePrice: 900, deskPrice: 600 },
  { id: 8, nameAr: 'بشار', nameEn: 'Béchar', homePrice: 1100, deskPrice: 700 },
  { id: 9, nameAr: 'البليدة', nameEn: 'Blida', homePrice: 500, deskPrice: 350 },
  { id: 10, nameAr: 'البويرة', nameEn: 'Bouira', homePrice: 700, deskPrice: 450 },
  { id: 11, nameAr: 'تمنراست', nameEn: 'Tamanrasset', homePrice: 1500, deskPrice: 1000 },
  { id: 12, nameAr: 'تبسة', nameEn: 'Tébessa', homePrice: 900, deskPrice: 600 },
  { id: 13, nameAr: 'تلمسان', nameEn: 'Tlemcen', homePrice: 850, deskPrice: 550 },
  { id: 14, nameAr: 'تيارت', nameEn: 'Tiaret', homePrice: 850, deskPrice: 550 },
  { id: 15, nameAr: 'تيزي وزو', nameEn: 'Tizi Ouzou', homePrice: 700, deskPrice: 450 },
  { id: 16, nameAr: 'الجزائر', nameEn: 'Algiers', homePrice: 400, deskPrice: 200 },
  { id: 17, nameAr: 'الجلفة', nameEn: 'Djelfa', homePrice: 900, deskPrice: 600 },
  { id: 18, nameAr: 'جيجل', nameEn: 'Jijel', homePrice: 850, deskPrice: 550 },
  { id: 19, nameAr: 'سطيف', nameEn: 'Sétif', homePrice: 800, deskPrice: 500 },
  { id: 20, nameAr: 'سعيدة', nameEn: 'Saïda', homePrice: 850, deskPrice: 550 },
  { id: 21, nameAr: 'سكيكدة', nameEn: 'Skikda', homePrice: 850, deskPrice: 550 },
  { id: 22, nameAr: 'سيدي بلعباس', nameEn: 'Sidi Bel Abbès', homePrice: 850, deskPrice: 550 },
  { id: 23, nameAr: 'عنابة', nameEn: 'Annaba', homePrice: 850, deskPrice: 550 },
  { id: 24, nameAr: 'قالمة', nameEn: 'Guelma', homePrice: 850, deskPrice: 550 },
  { id: 25, nameAr: 'قسنطينة', nameEn: 'Constantine', homePrice: 800, deskPrice: 500 },
  { id: 26, nameAr: 'المدية', nameEn: 'Médéa', homePrice: 700, deskPrice: 450 },
  { id: 27, nameAr: 'مستغانم', nameEn: 'Mostaganem', homePrice: 800, deskPrice: 500 },
  { id: 28, nameAr: 'المسيلة', nameEn: 'M\'Sila', homePrice: 850, deskPrice: 550 },
  { id: 29, nameAr: 'معسكر', nameEn: 'Mascara', homePrice: 850, deskPrice: 550 },
  { id: 30, nameAr: 'ورقلة', nameEn: 'Ouargla', homePrice: 1000, deskPrice: 700 },
  { id: 31, nameAr: 'وهران', nameEn: 'Oran', homePrice: 800, deskPrice: 500 },
  { id: 32, nameAr: 'البيض', nameEn: 'El Bayadh', homePrice: 1000, deskPrice: 700 },
  { id: 33, nameAr: 'إيليزي', nameEn: 'Illizi', homePrice: 1200, deskPrice: 800 },
  { id: 34, nameAr: 'برج بوعريريج', nameEn: 'Bordj Bou Arréridj', homePrice: 800, deskPrice: 500 },
  { id: 35, nameAr: 'بومرداس', nameEn: 'Boumerdès', homePrice: 600, deskPrice: 400 },
  { id: 36, nameAr: 'الطارف', nameEn: 'El Tarf', homePrice: 850, deskPrice: 550 },
  { id: 37, nameAr: 'تندوف', nameEn: 'Tindouf', homePrice: 1200, deskPrice: 800 },
  { id: 38, nameAr: 'تسمسيلت', nameEn: 'Tissemsilt', homePrice: 850, deskPrice: 550 },
  { id: 39, nameAr: 'الوادي', nameEn: 'El Oued', homePrice: 1000, deskPrice: 700 },
  { id: 40, nameAr: 'خنشلة', nameEn: 'Khenchela', homePrice: 850, deskPrice: 550 },
  { id: 41, nameAr: 'سوق أهراس', nameEn: 'Souk Ahras', homePrice: 850, deskPrice: 550 },
  { id: 42, nameAr: 'تيبازة', nameEn: 'Tipaza', homePrice: 600, deskPrice: 400 },
  { id: 43, nameAr: 'ميلة', nameEn: 'Mila', homePrice: 800, deskPrice: 500 },
  { id: 44, nameAr: 'عين الدفلى', nameEn: 'Aïn Defla', homePrice: 750, deskPrice: 450 },
  { id: 45, nameAr: 'النعامة', nameEn: 'Naâma', homePrice: 1000, deskPrice: 700 },
  { id: 46, nameAr: 'عين تموشنت', nameEn: 'Aïn Témouchent', homePrice: 850, deskPrice: 550 },
  { id: 47, nameAr: 'غرداية', nameEn: 'Ghardaïa', homePrice: 1000, deskPrice: 700 },
  { id: 48, nameAr: 'غليزان', nameEn: 'Relizane', homePrice: 800, deskPrice: 500 },
  { id: 49, nameAr: 'تيميمون', nameEn: 'Timimoun', homePrice: 1200, deskPrice: 800 },
  { id: 50, nameAr: 'برج باجي مختار', nameEn: 'Bordj Badji Mokhtar', homePrice: 1500, deskPrice: 1000 },
  { id: 51, nameAr: 'أولاد جلال', nameEn: 'Ouled Djellal', homePrice: 900, deskPrice: 600 },
  { id: 52, nameAr: 'بني عباس', nameEn: 'Béni Abbès', homePrice: 1100, deskPrice: 700 },
  { id: 53, nameAr: 'عين صالح', nameEn: 'In Salah', homePrice: 1300, deskPrice: 900 },
  { id: 54, nameAr: 'عين قزام', nameEn: 'In Guezzam', homePrice: 1500, deskPrice: 1000 },
  { id: 55, nameAr: 'تقرت', nameEn: 'Touggourt', homePrice: 1000, deskPrice: 700 },
  { id: 56, nameAr: 'جانت', nameEn: 'Djanet', homePrice: 1400, deskPrice: 900 },
  { id: 57, nameAr: 'المغير', nameEn: 'El M\'Ghair', homePrice: 900, deskPrice: 600 },
  { id: 58, nameAr: 'المنيعة', nameEn: 'El Meniaa', homePrice: 1000, deskPrice: 700 },
];
