export const algeriaWilayas = [
  { id: 1, nameAr: 'أدرار', nameEn: 'Adrar', deskPrice: 900, homePrice: 1100 },
  { id: 2, nameAr: 'الشلف', nameEn: 'Chlef', deskPrice: 400, homePrice: 700 },
  { id: 3, nameAr: 'الأغواط', nameEn: 'Laghouat', deskPrice: 500, homePrice: 900 },
  { id: 4, nameAr: 'أم البواقي', nameEn: 'Oum El Bouaghi', deskPrice: 500, homePrice: 700 },
  { id: 5, nameAr: 'باتنة', nameEn: 'Batna', deskPrice: 400, homePrice: 600 },
  { id: 6, nameAr: 'بجاية', nameEn: 'Béjaïa', deskPrice: 400, homePrice: 600 },
  { id: 7, nameAr: 'بسكرة', nameEn: 'Biskra', deskPrice: 500, homePrice: 800 },
  { id: 8, nameAr: 'بشار', nameEn: 'Béchar', deskPrice: 900, homePrice: 1100 },
  { id: 9, nameAr: 'البليدة', nameEn: 'Blida', deskPrice: 400, homePrice: 600 },
  { id: 10, nameAr: 'البويرة', nameEn: 'Bouïra', deskPrice: 400, homePrice: 700 },
  { id: 11, nameAr: 'تمنراست', nameEn: 'Tamanrasset', deskPrice: 900, homePrice: 1300 },
  { id: 12, nameAr: 'تبسة', nameEn: 'Tébessa', deskPrice: 400, homePrice: 800 },
  { id: 13, nameAr: 'تلمسان', nameEn: 'Tlemcen', deskPrice: 400, homePrice: 800 },
  { id: 14, nameAr: 'تيارت', nameEn: 'Tiaret', deskPrice: 400, homePrice: 800 },
  { id: 15, nameAr: 'تيزي وزو', nameEn: 'Tizi Ouzou', deskPrice: 400, homePrice: 700 },
  { id: 16, nameAr: 'الجزائر', nameEn: 'Alger', deskPrice: 350, homePrice: 500 },
  { id: 17, nameAr: 'الجلفة', nameEn: 'Djelfa', deskPrice: 500, homePrice: 900 },
  { id: 18, nameAr: 'جيجل', nameEn: 'Jijel', deskPrice: 400, homePrice: 600 },
  { id: 19, nameAr: 'سطيف', nameEn: 'Sétif', deskPrice: 400, homePrice: 600 },
  { id: 20, nameAr: 'سعيدة', nameEn: 'Saïda', deskPrice: 400, homePrice: 800 },
  { id: 21, nameAr: 'سكيكدة', nameEn: 'Skikda', deskPrice: 400, homePrice: 650 },
  { id: 22, nameAr: 'سيدي بلعباس', nameEn: 'Sidi Bel Abbès', deskPrice: 400, homePrice: 800 },
  { id: 23, nameAr: 'عنابة', nameEn: 'Annaba', deskPrice: 400, homePrice: 700 },
  { id: 24, nameAr: 'قالمة', nameEn: 'Guelma', deskPrice: 400, homePrice: 700 },
  { id: 25, nameAr: 'قسنطينة', nameEn: 'Constantine', deskPrice: 400, homePrice: 600 },
  { id: 26, nameAr: 'المدية', nameEn: 'Médéa', deskPrice: 400, homePrice: 700 },
  { id: 27, nameAr: 'مستغانم', nameEn: 'Mostaganem', deskPrice: 400, homePrice: 700 },
  { id: 28, nameAr: 'المسيلة', nameEn: 'M\'Sila', deskPrice: 400, homePrice: 700 },
  { id: 29, nameAr: 'معسكر', nameEn: 'Mascara', deskPrice: 400, homePrice: 700 },
  { id: 30, nameAr: 'ورقلة', nameEn: 'Ouargla', deskPrice: 500, homePrice: 1000 },
  { id: 31, nameAr: 'وهران', nameEn: 'Oran', deskPrice: 400, homePrice: 700 },
  { id: 32, nameAr: 'البيض', nameEn: 'El Bayadh', deskPrice: 700, homePrice: 1000 },
  { id: 33, nameAr: 'إليزي', nameEn: 'Illizi', deskPrice: 1500, homePrice: 1500 },
  { id: 34, nameAr: 'برج بوعريريج', nameEn: 'Bordj Bou Arréridj', deskPrice: 400, homePrice: 600 },
  { id: 35, nameAr: 'بومرداس', nameEn: 'Boumerdès', deskPrice: 400, homePrice: 700 },
  { id: 36, nameAr: 'الطارف', nameEn: 'El Tarf', deskPrice: 400, homePrice: 700 },
  { id: 37, nameAr: 'تندوف', nameEn: 'Tindouf', deskPrice: 1000, homePrice: 1300 },
  { id: 38, nameAr: 'تسمسيلت', nameEn: 'Tissemsilt', deskPrice: 400, homePrice: 800 },
  { id: 39, nameAr: 'الوادي', nameEn: 'El Oued', deskPrice: 600, homePrice: 900 },
  { id: 40, nameAr: 'خنشلة', nameEn: 'Khenchela', deskPrice: 500, homePrice: 700 },
  { id: 41, nameAr: 'سوق أهراس', nameEn: 'Souk Ahras', deskPrice: 500, homePrice: 800 },
  { id: 42, nameAr: 'تيبازة', nameEn: 'Tipaza', deskPrice: 400, homePrice: 700 },
  { id: 43, nameAr: 'ميلة', nameEn: 'Mila', deskPrice: 400, homePrice: 600 },
  { id: 44, nameAr: 'عين الدفلى', nameEn: 'Aïn Defla', deskPrice: 400, homePrice: 700 },
  { id: 45, nameAr: 'النعامة', nameEn: 'Naâma', deskPrice: 600, homePrice: 1000 },
  { id: 46, nameAr: 'عين تموشنت', nameEn: 'Aïn Témouchent', deskPrice: 400, homePrice: 800 },
  { id: 47, nameAr: 'غرداية', nameEn: 'Ghardaïa', deskPrice: 500, homePrice: 900 },
  { id: 48, nameAr: 'غليزان', nameEn: 'Relizane', deskPrice: 400, homePrice: 700 },
  { id: 49, nameAr: 'تيميمون', nameEn: 'Timimoun', deskPrice: 800, homePrice: 1300 },
  { id: 50, nameAr: 'برج باجي مختار', nameEn: 'Bordj Badji Mokhtar', deskPrice: null, homePrice: null },
  { id: 51, nameAr: 'أولاد جلال', nameEn: 'Ouled Djellal', deskPrice: 650, homePrice: 900 },
  { id: 52, nameAr: 'بني عباس', nameEn: 'Béni Abbès', deskPrice: null, homePrice: 1300 },
  { id: 53, nameAr: 'عين صالح', nameEn: 'In Salah', deskPrice: 600, homePrice: 1300 },
  { id: 54, nameAr: 'عين قزام', nameEn: 'In Guezzam', deskPrice: null, homePrice: null },
  { id: 55, nameAr: 'توقرت', nameEn: 'Touggourt', deskPrice: null, homePrice: 900 },
  { id: 56, nameAr: 'جانت', nameEn: 'Djanet', deskPrice: null, homePrice: null },
  { id: 57, nameAr: 'المغير', nameEn: 'El M\'Ghair', deskPrice: null, homePrice: 900 },
  { id: 58, nameAr: 'المنيعة', nameEn: 'El Meniaa', deskPrice: 800, homePrice: 1000 },
];
